[package]
name = "set-theory"
version = "0.1.0"
edition = "2021"
description = "type system set theory"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
